branches:
  only:
    - injective

language: node_js

sudo: false

node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - git config --global user.name "IniZio"
  - git config --global user.email "digit4free@gmail.com"
  - git clone --branch gh-pages https://github.com/IniZio/Analax.git dist

install:
  - npm install

script:
  - npm run build

after_script:
  - cd dist
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
